/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dudge_slave_dtest_SolutionLauncher */

#ifndef _Included_dudge_slave_dtest_SolutionLauncher
#define _Included_dudge_slave_dtest_SolutionLauncher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dudge_slave_dtest_SolutionLauncher
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_dudge_slave_dtest_SolutionLauncher_init
  (JNIEnv *, jclass);

/*
 * Class:     dudge_slave_dtest_SolutionLauncher
 * Method:    createContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dudge_slave_dtest_SolutionLauncher_createContext
  (JNIEnv *, jclass);

/*
 * Class:     dudge_slave_dtest_SolutionLauncher
 * Method:    freeContext
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dudge_slave_dtest_SolutionLauncher_freeContext
  (JNIEnv *, jclass, jint);

/*
 * Class:     dudge_slave_dtest_SolutionLauncher
 * Method:    checkSolution
 * Signature: (Ldudge/slave/dtest/CheckingLimits;Ljava/lang/String;Ljava/io/InputStream;Ljava/io/OutputStream;Ljava/io/Writer;)Ldudge/slave/dtest/CheckingResult;
 */
JNIEXPORT jobject JNICALL Java_dudge_slave_dtest_SolutionLauncher_checkSolution
  (JNIEnv *, jobject, jobject, jstring, jobject, jobject, jobject);

/*
 * Class:     dudge_slave_dtest_SolutionLauncher
 * Method:    createTemporaryDirectory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dudge_slave_dtest_SolutionLauncher_createTemporaryDirectory
  (JNIEnv *, jobject);

/*
 * Class:     dudge_slave_dtest_SolutionLauncher
 * Method:    deleteTemporaryDirectory
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_dudge_slave_dtest_SolutionLauncher_deleteTemporaryDirectory
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
